/* ImageNet-Klassen (MobileNet) auf Deutsch: [Name, Kategorie] – Index = Klassennummer */
window.WIW_LABELS = [
["Schleie","Tier"],
["Goldfisch","Tier"],
["Weißer Hai","Tier"],
["Tigerhai","Tier"],
["Hammerhai","Tier"],
["Zitterrochen","Tier"],
["Stachelrochen","Tier"],
["Hahn","Tier"],
["Huhn","Tier"],
["Strauß","Tier"],
["Bergfink","Tier"],
["Stieglitz","Tier"],
["Hausgimpel","Tier"],
["Junko","Tier"],
["Indigofink","Tier"],
["Wanderdrossel","Tier"],
["Bülbül","Tier"],
["Eichelhäher","Tier"],
["Elster","Tier"],
["Meise","Tier"],
["Wasseramsel","Tier"],
["Milan","Tier"],
["Weißkopfseeadler","Tier"],
["Geier","Tier"],
["Bartkauz","Tier"],
["Feuersalamander","Tier"],
["Teichmolch","Tier"],
["Molch","Tier"],
["Salamander","Tier"],
["Axolotl","Tier"],
["Ochsenfrosch","Tier"],
["Laubfrosch","Tier"],
["Frosch","Tier"],
["Meeresschildkröte","Tier"],
["Lederschildkröte","Tier"],
["Schildkröte","Tier"],
["Wasserschildkröte","Tier"],
["Dosenschildkröte","Tier"],
["Gecko","Tier"],
["Leguan","Tier"],
["Anolis","Tier"],
["Rennechse","Tier"],
["Agame","Tier"],
["Kragenechse","Tier"],
["Echse","Tier"],
["Gila-Krustenechse","Tier"],
["Smaragdeidechse","Tier"],
["Chamäleon","Tier"],
["Komodowaran","Tier"],
["Krokodil","Tier"],
["Alligator","Tier"],
["Dinosaurier","Spielzeug"],
["Wurmnatter","Tier"],
["Ringhalsnatter","Tier"],
["Hakennasennatter","Tier"],
["Grasnatter","Tier"],
["Königsnatter","Tier"],
["Strumpfbandnatter","Tier"],
["Wassernatter","Tier"],
["Peitschennatter","Tier"],
["Nachtnatter","Tier"],
["Boa","Tier"],
["Python","Tier"],
["Kobra","Tier"],
["Mamba","Tier"],
["Seeschlange","Tier"],
["Hornviper","Tier"],
["Klapperschlange","Tier"],
["Seitenwinder","Tier"],
["Fossil","Deko"],
["Weberknecht","Tier"],
["Skorpion","Tier"],
["Gartenspinne","Tier"],
["Scheunenspinne","Tier"],
["Kreuzspinne","Tier"],
["Schwarze Witwe","Tier"],
["Vogelspinne","Tier"],
["Wolfspinne","Tier"],
["Zecke","Tier"],
["Hundertfüßer","Tier"],
["Birkhuhn","Tier"],
["Schneehuhn","Tier"],
["Kragenhuhn","Tier"],
["Präriehuhn","Tier"],
["Pfau","Tier"],
["Wachtel","Tier"],
["Rebhuhn","Tier"],
["Graupapagei","Tier"],
["Ara","Tier"],
["Kakadu","Tier"],
["Lori","Tier"],
["Spornkuckuck","Tier"],
["Bienenfresser","Tier"],
["Nashornvogel","Tier"],
["Kolibri","Tier"],
["Glanzvogel","Tier"],
["Tukan","Tier"],
["Erpel","Tier"],
["Mittelsäger","Tier"],
["Gans","Tier"],
["Schwarzer Schwan","Tier"],
["Elefant","Tier"],
["Ameisenigel","Tier"],
["Schnabeltier","Tier"],
["Wallaby","Tier"],
["Koala","Tier"],
["Wombat","Tier"],
["Qualle","Tier"],
["Seeanemone","Tier"],
["Hirnkoralle","Tier"],
["Plattwurm","Tier"],
["Fadenwurm","Tier"],
["Muschel","Deko"],
["Schnecke","Tier"],
["Nacktschnecke","Tier"],
["Meeresnacktschnecke","Tier"],
["Käferschnecke","Tier"],
["Nautilus","Tier"],
["Taschenkrebs","Tier"],
["Felsenkrabbe","Tier"],
["Winkerkrabbe","Tier"],
["Königskrabbe","Tier"],
["Hummer","Tier"],
["Languste","Tier"],
["Flusskrebs","Tier"],
["Einsiedlerkrebs","Tier"],
["Assel","Tier"],
["Weißstorch","Tier"],
["Schwarzstorch","Tier"],
["Löffler","Tier"],
["Flamingo","Tier"],
["Blaureiher","Tier"],
["Silberreiher","Tier"],
["Rohrdommel","Tier"],
["Kranich","Tier"],
["Rallenkranich","Tier"],
["Purpurhuhn","Tier"],
["Blässhuhn","Tier"],
["Trappe","Tier"],
["Steinwälzer","Tier"],
["Alpenstrandläufer","Tier"],
["Rotschenkel","Tier"],
["Schlammläufer","Tier"],
["Austernfischer","Tier"],
["Pelikan","Tier"],
["Königspinguin","Tier"],
["Albatros","Tier"],
["Grauwal","Tier"],
["Orca","Tier"],
["Seekuh","Tier"],
["Seelöwe","Tier"],
["Chihuahua","Tier"],
["Japan-Chin","Tier"],
["Malteser","Tier"],
["Pekinese","Tier"],
["Shih Tzu","Tier"],
["King Charles Spaniel","Tier"],
["Papillon","Tier"],
["Toy-Terrier","Tier"],
["Rhodesian Ridgeback","Tier"],
["Afghanischer Windhund","Tier"],
["Basset","Tier"],
["Beagle","Tier"],
["Bluthund","Tier"],
["Bluetick Coonhound","Tier"],
["Coonhound","Tier"],
["Walker Foxhound","Tier"],
["Englischer Foxhound","Tier"],
["Redbone Coonhound","Tier"],
["Barsoi","Tier"],
["Irischer Wolfshund","Tier"],
["Italienisches Windspiel","Tier"],
["Whippet","Tier"],
["Podenco","Tier"],
["Elchhund","Tier"],
["Otterhund","Tier"],
["Saluki","Tier"],
["Deerhound","Tier"],
["Weimaraner","Tier"],
["Staffordshire Bullterrier","Tier"],
["American Staffordshire Terrier","Tier"],
["Bedlington Terrier","Tier"],
["Border Terrier","Tier"],
["Kerry Blue Terrier","Tier"],
["Irish Terrier","Tier"],
["Norfolk Terrier","Tier"],
["Norwich Terrier","Tier"],
["Yorkshire Terrier","Tier"],
["Foxterrier","Tier"],
["Lakeland Terrier","Tier"],
["Sealyham Terrier","Tier"],
["Airedale Terrier","Tier"],
["Cairn Terrier","Tier"],
["Australian Terrier","Tier"],
["Dandie Dinmont Terrier","Tier"],
["Boston Terrier","Tier"],
["Zwergschnauzer","Tier"],
["Riesenschnauzer","Tier"],
["Schnauzer","Tier"],
["Scottish Terrier","Tier"],
["Tibet-Terrier","Tier"],
["Silky Terrier","Tier"],
["Wheaten Terrier","Tier"],
["West Highland Terrier","Tier"],
["Lhasa Apso","Tier"],
["Flat Coated Retriever","Tier"],
["Curly Coated Retriever","Tier"],
["Golden Retriever","Tier"],
["Labrador","Tier"],
["Chesapeake Bay Retriever","Tier"],
["Deutsch Kurzhaar","Tier"],
["Magyar Vizsla","Tier"],
["English Setter","Tier"],
["Irish Setter","Tier"],
["Gordon Setter","Tier"],
["Epagneul Breton","Tier"],
["Clumber Spaniel","Tier"],
["Springer Spaniel","Tier"],
["Welsh Springer Spaniel","Tier"],
["Cocker Spaniel","Tier"],
["Sussex Spaniel","Tier"],
["Irish Water Spaniel","Tier"],
["Kuvasz","Tier"],
["Schipperke","Tier"],
["Groenendael","Tier"],
["Malinois","Tier"],
["Briard","Tier"],
["Kelpie","Tier"],
["Komondor","Tier"],
["Bobtail","Tier"],
["Sheltie","Tier"],
["Collie","Tier"],
["Border Collie","Tier"],
["Bouvier des Flandres","Tier"],
["Rottweiler","Tier"],
["Schäferhund","Tier"],
["Dobermann","Tier"],
["Zwergpinscher","Tier"],
["Großer Schweizer Sennenhund","Tier"],
["Berner Sennenhund","Tier"],
["Appenzeller Sennenhund","Tier"],
["Entlebucher Sennenhund","Tier"],
["Boxer","Tier"],
["Bullmastiff","Tier"],
["Tibet-Dogge","Tier"],
["Französische Bulldogge","Tier"],
["Deutsche Dogge","Tier"],
["Bernhardiner","Tier"],
["Eskimohund","Tier"],
["Alaskan Malamute","Tier"],
["Husky","Tier"],
["Dalmatiner","Tier"],
["Affenpinscher","Tier"],
["Basenji","Tier"],
["Mops","Tier"],
["Leonberger","Tier"],
["Neufundländer","Tier"],
["Pyrenäenberghund","Tier"],
["Samojede","Tier"],
["Zwergspitz","Tier"],
["Chow-Chow","Tier"],
["Wolfsspitz","Tier"],
["Griffon","Tier"],
["Corgi","Tier"],
["Cardigan Corgi","Tier"],
["Toypudel","Tier"],
["Zwergpudel","Tier"],
["Pudel","Tier"],
["Nackthund","Tier"],
["Wolf","Tier"],
["Polarwolf","Tier"],
["Rotwolf","Tier"],
["Kojote","Tier"],
["Dingo","Tier"],
["Rothund","Tier"],
["Afrikanischer Wildhund","Tier"],
["Hyäne","Tier"],
["Rotfuchs","Tier"],
["Kitfuchs","Tier"],
["Polarfuchs","Tier"],
["Graufuchs","Tier"],
["Getigerte Katze","Tier"],
["Tigerkatze","Tier"],
["Perserkatze","Tier"],
["Siamkatze","Tier"],
["Ägyptische Mau","Tier"],
["Puma","Tier"],
["Luchs","Tier"],
["Leopard","Tier"],
["Schneeleopard","Tier"],
["Jaguar","Tier"],
["Löwe","Tier"],
["Tiger","Tier"],
["Gepard","Tier"],
["Braunbär","Tier"],
["Schwarzbär","Tier"],
["Eisbär","Tier"],
["Lippenbär","Tier"],
["Mungo","Tier"],
["Erdmännchen","Tier"],
["Sandlaufkäfer","Tier"],
["Marienkäfer","Tier"],
["Laufkäfer","Tier"],
["Bockkäfer","Tier"],
["Blattkäfer","Tier"],
["Mistkäfer","Tier"],
["Nashornkäfer","Tier"],
["Rüsselkäfer","Tier"],
["Fliege","Tier"],
["Biene","Tier"],
["Ameise","Tier"],
["Heuschrecke","Tier"],
["Grille","Tier"],
["Stabschrecke","Tier"],
["Kakerlake","Tier"],
["Gottesanbeterin","Tier"],
["Zikade","Tier"],
["Zwergzikade","Tier"],
["Florfliege","Tier"],
["Libelle","Tier"],
["Kleinlibelle","Tier"],
["Admiral","Tier"],
["Schmetterling","Tier"],
["Monarchfalter","Tier"],
["Kohlweißling","Tier"],
["Zitronenfalter","Tier"],
["Bläuling","Tier"],
["Seestern","Tier"],
["Seeigel","Tier"],
["Seegurke","Tier"],
["Kaninchen","Tier"],
["Hase","Tier"],
["Angorakaninchen","Tier"],
["Hamster","Tier"],
["Stachelschwein","Tier"],
["Eichhörnchen","Tier"],
["Murmeltier","Tier"],
["Biber","Tier"],
["Meerschweinchen","Tier"],
["Pferd","Tier"],
["Zebra","Tier"],
["Schwein","Tier"],
["Wildschwein","Tier"],
["Warzenschwein","Tier"],
["Nilpferd","Tier"],
["Rind","Tier"],
["Wasserbüffel","Tier"],
["Bison","Tier"],
["Widder","Tier"],
["Dickhornschaf","Tier"],
["Steinbock","Tier"],
["Kuhantilope","Tier"],
["Impala","Tier"],
["Gazelle","Tier"],
["Dromedar","Tier"],
["Lama","Tier"],
["Wiesel","Tier"],
["Nerz","Tier"],
["Iltis","Tier"],
["Frettchen","Tier"],
["Otter","Tier"],
["Stinktier","Tier"],
["Dachs","Tier"],
["Gürteltier","Tier"],
["Faultier","Tier"],
["Orang-Utan","Tier"],
["Gorilla","Tier"],
["Schimpanse","Tier"],
["Gibbon","Tier"],
["Siamang","Tier"],
["Meerkatze","Tier"],
["Husarenaffe","Tier"],
["Pavian","Tier"],
["Makak","Tier"],
["Langur","Tier"],
["Stummelaffe","Tier"],
["Nasenaffe","Tier"],
["Krallenaffe","Tier"],
["Kapuzineraffe","Tier"],
["Brüllaffe","Tier"],
["Springaffe","Tier"],
["Klammeraffe","Tier"],
["Totenkopfäffchen","Tier"],
["Katta","Tier"],
["Indri","Tier"],
["Indischer Elefant","Tier"],
["Afrikanischer Elefant","Tier"],
["Roter Panda","Tier"],
["Panda","Tier"],
["Snoek","Tier"],
["Aal","Tier"],
["Lachs","Tier"],
["Kaiserfisch","Tier"],
["Clownfisch","Tier"],
["Stör","Tier"],
["Knochenhecht","Tier"],
["Rotfeuerfisch","Tier"],
["Kugelfisch","Tier"],
["Abakus","Spielzeug"],
["Abaya","Kleidung"],
["Talar","Kleidung"],
["Akkordeon","Musik"],
["Gitarre","Musik"],
["Flugzeugträger","Fahrzeug"],
["Flugzeug","Fahrzeug"],
["Luftschiff","Fahrzeug"],
["Altar","Sonstiges"],
["Krankenwagen","Fahrzeug"],
["Amphibienfahrzeug","Fahrzeug"],
["Uhr","Haushalt"],
["Bienenstock","Garten"],
["Schürze","Küche"],
["Mülleimer","Haushalt"],
["Sturmgewehr","Sonstiges"],
["Rucksack","Taschen"],
["Backwaren","Lebensmittel"],
["Schwebebalken","Sport & Freizeit"],
["Luftballon","Spielzeug"],
["Kugelschreiber","Büro"],
["Pflaster","Bad & Pflege"],
["Banjo","Musik"],
["Treppengeländer","Sonstiges"],
["Langhantel","Sport & Freizeit"],
["Friseurstuhl","Möbel"],
["Friseursalon","Sonstiges"],
["Scheune","Sonstiges"],
["Barometer","Haushalt"],
["Fass","Haushalt"],
["Schubkarre","Garten"],
["Baseball","Sport & Freizeit"],
["Basketball","Sport & Freizeit"],
["Stubenwagen","Möbel"],
["Fagott","Musik"],
["Badekappe","Sport & Freizeit"],
["Badetuch","Bad & Pflege"],
["Badewanne","Bad & Pflege"],
["Kombi","Fahrzeug"],
["Leuchtturm","Sonstiges"],
["Becherglas","Küche"],
["Bärenfellmütze","Kleidung"],
["Bierflasche","Lebensmittel"],
["Bierglas","Küche"],
["Glockenturm","Sonstiges"],
["Lätzchen","Kleidung"],
["Tandem","Fahrzeug"],
["Bikini","Kleidung"],
["Ordner","Büro"],
["Fernglas","Sport & Freizeit"],
["Vogelhaus","Garten"],
["Bootshaus","Sonstiges"],
["Bob","Sport & Freizeit"],
["Westernkrawatte","Kleidung"],
["Haube","Kleidung"],
["Bücherregal","Möbel"],
["Bücher","Bücher & Medien"],
["Kronkorken","Küche"],
["Bogen","Sport & Freizeit"],
["Fliege","Kleidung"],
["Gedenktafel","Deko"],
["BH","Kleidung"],
["Wellenbrecher","Sonstiges"],
["Brustpanzer","Sonstiges"],
["Besen","Haushalt"],
["Eimer","Haushalt"],
["Gürtelschnalle","Kleidung"],
["Schutzweste","Kleidung"],
["Schnellzug","Fahrzeug"],
["Fleisch","Lebensmittel"],
["Taxi","Fahrzeug"],
["Kessel","Küche"],
["Kerze","Deko"],
["Kanone","Sonstiges"],
["Kanu","Sport & Freizeit"],
["Dosenöffner","Küche"],
["Strickjacke","Kleidung"],
["Autospiegel","Fahrzeug"],
["Karussell","Sonstiges"],
["Werkzeugkasten","Werkzeug"],
["Karton","Haushalt"],
["Autorad","Fahrzeug"],
["Geldautomat","Sonstiges"],
["Kassette","Bücher & Medien"],
["Kassettenrekorder","Elektronik"],
["Burg","Sonstiges"],
["Katamaran","Fahrzeug"],
["CD-Player","Elektronik"],
["Cello","Musik"],
["Handy","Elektronik"],
["Kette","Werkzeug"],
["Maschendrahtzaun","Garten"],
["Kettenhemd","Sonstiges"],
["Kettensäge","Werkzeug"],
["Truhe","Möbel"],
["Kommode","Möbel"],
["Windspiel","Deko"],
["Vitrine","Möbel"],
["Weihnachtsstrumpf","Deko"],
["Kirche","Sonstiges"],
["Kino","Sonstiges"],
["Hackbeil","Küche"],
["Felsenwohnung","Sonstiges"],
["Umhang","Kleidung"],
["Clog","Schuhe"],
["Cocktailshaker","Küche"],
["Kaffeebecher","Küche"],
["Kaffeekanne","Küche"],
["Spirale","Sonstiges"],
["Zahlenschloss","Haushalt"],
["Tastatur","Elektronik"],
["Süßigkeiten","Lebensmittel"],
["Containerschiff","Fahrzeug"],
["Cabrio","Fahrzeug"],
["Korkenzieher","Küche"],
["Trompete","Musik"],
["Cowboystiefel","Schuhe"],
["Cowboyhut","Kleidung"],
["Wiege","Möbel"],
["Kran","Sonstiges"],
["Helm","Sport & Freizeit"],
["Kiste","Haushalt"],
["Kinderbett","Möbel"],
["Schongarer","Küche"],
["Krocketkugel","Sport & Freizeit"],
["Krücke","Haushalt"],
["Kürass","Sonstiges"],
["Staudamm","Sonstiges"],
["Schreibtisch","Möbel"],
["Computer","Elektronik"],
["Telefon","Elektronik"],
["Windel","Bad & Pflege"],
["Digitaluhr","Elektronik"],
["Armbanduhr","Kleidung"],
["Esstisch","Möbel"],
["Spültuch","Küche"],
["Spülmaschine","Küche"],
["Scheibenbremse","Fahrzeug"],
["Anlegestelle","Sonstiges"],
["Hundeschlitten","Fahrzeug"],
["Kuppel","Sonstiges"],
["Fußmatte","Haushalt"],
["Bohrinsel","Sonstiges"],
["Trommel","Musik"],
["Trommelstock","Musik"],
["Hantel","Sport & Freizeit"],
["Schmortopf","Küche"],
["Ventilator","Haushalt"],
["E-Gitarre","Musik"],
["E-Lok","Fahrzeug"],
["Fernsehschrank","Möbel"],
["Briefumschlag","Büro"],
["Espressomaschine","Küche"],
["Puder","Bad & Pflege"],
["Federboa","Kleidung"],
["Aktenschrank","Büro"],
["Feuerlöschboot","Fahrzeug"],
["Feuerwehrauto","Fahrzeug"],
["Kaminschirm","Haushalt"],
["Fahnenmast","Sonstiges"],
["Querflöte","Musik"],
["Klappstuhl","Möbel"],
["Footballhelm","Sport & Freizeit"],
["Gabelstapler","Fahrzeug"],
["Springbrunnen","Garten"],
["Füller","Büro"],
["Himmelbett","Möbel"],
["Güterwagen","Fahrzeug"],
["Waldhorn","Musik"],
["Pfanne","Küche"],
["Pelzmantel","Kleidung"],
["Müllauto","Fahrzeug"],
["Gasmaske","Sonstiges"],
["Zapfsäule","Sonstiges"],
["Weinglas","Küche"],
["Gokart","Fahrzeug"],
["Golfball","Sport & Freizeit"],
["Golfwagen","Fahrzeug"],
["Gondel","Fahrzeug"],
["Gong","Musik"],
["Abendkleid","Kleidung"],
["Flügel","Musik"],
["Gewächshaus","Garten"],
["Kühlergrill","Fahrzeug"],
["Vorräte","Lebensmittel"],
["Guillotine","Sonstiges"],
["Haarspange","Bad & Pflege"],
["Haarspray","Bad & Pflege"],
["Halbkettenfahrzeug","Fahrzeug"],
["Hammer","Werkzeug"],
["Korb","Haushalt"],
["Föhn","Bad & Pflege"],
["PDA","Elektronik"],
["Taschentuch","Kleidung"],
["Festplatte","Elektronik"],
["Mundharmonika","Musik"],
["Harfe","Musik"],
["Mähdrescher","Fahrzeug"],
["Beil","Werkzeug"],
["Holster","Sonstiges"],
["Heimkino","Elektronik"],
["Honigwabe","Lebensmittel"],
["Haken","Haushalt"],
["Reifrock","Kleidung"],
["Reck","Sport & Freizeit"],
["Pferdekutsche","Fahrzeug"],
["Sanduhr","Deko"],
["MP3-Player","Elektronik"],
["Bügeleisen","Haushalt"],
["Kürbislaterne","Deko"],
["Jeans","Kleidung"],
["Geländewagen","Fahrzeug"],
["T-Shirt","Kleidung"],
["Puzzle","Spielzeug"],
["Rikscha","Fahrzeug"],
["Joystick","Elektronik"],
["Kimono","Kleidung"],
["Knieschoner","Sport & Freizeit"],
["Knoten","Sonstiges"],
["Kittel","Kleidung"],
["Schöpfkelle","Küche"],
["Lampenschirm","Haushalt"],
["Laptop","Elektronik"],
["Rasenmäher","Garten"],
["Objektivdeckel","Elektronik"],
["Brieföffner","Büro"],
["Bibliothek","Bücher & Medien"],
["Rettungsboot","Fahrzeug"],
["Feuerzeug","Haushalt"],
["Limousine","Fahrzeug"],
["Kreuzfahrtschiff","Fahrzeug"],
["Lippenstift","Bad & Pflege"],
["Slipper","Schuhe"],
["Bodylotion","Bad & Pflege"],
["Lautsprecher","Elektronik"],
["Lupe","Haushalt"],
["Sägewerk","Sonstiges"],
["Kompass","Sport & Freizeit"],
["Posttasche","Taschen"],
["Briefkasten","Haushalt"],
["Gymnastikanzug","Kleidung"],
["Badeanzug","Kleidung"],
["Gullydeckel","Sonstiges"],
["Rassel","Musik"],
["Xylophon","Musik"],
["Maske","Deko"],
["Streichholz","Haushalt"],
["Maibaum","Sonstiges"],
["Labyrinth","Sonstiges"],
["Messbecher","Küche"],
["Arzneischrank","Bad & Pflege"],
["Steinkreis","Sonstiges"],
["Mikrofon","Elektronik"],
["Mikrowelle","Küche"],
["Uniform","Kleidung"],
["Milchkanne","Küche"],
["Kleinbus","Fahrzeug"],
["Minirock","Kleidung"],
["Van","Fahrzeug"],
["Rakete","Sonstiges"],
["Fäustling","Kleidung"],
["Rührschüssel","Küche"],
["Mobilheim","Sonstiges"],
["Oldtimer","Fahrzeug"],
["Modem","Elektronik"],
["Kloster","Sonstiges"],
["Monitor","Elektronik"],
["Mofa","Fahrzeug"],
["Mörser","Küche"],
["Doktorhut","Kleidung"],
["Moschee","Sonstiges"],
["Moskitonetz","Haushalt"],
["Motorroller","Fahrzeug"],
["Mountainbike","Fahrzeug"],
["Zelt","Sport & Freizeit"],
["Computermaus","Elektronik"],
["Mausefalle","Haushalt"],
["Umzugswagen","Fahrzeug"],
["Maulkorb","Haushalt"],
["Nagel","Werkzeug"],
["Halskrause","Bad & Pflege"],
["Halskette","Kleidung"],
["Babyflasche","Haushalt"],
["Laptop","Elektronik"],
["Obelisk","Sonstiges"],
["Oboe","Musik"],
["Okarina","Musik"],
["Tacho","Fahrzeug"],
["Ölfilter","Fahrzeug"],
["Orgel","Musik"],
["Oszilloskop","Elektronik"],
["Rock","Kleidung"],
["Ochsenkarren","Fahrzeug"],
["Sauerstoffmaske","Sonstiges"],
["Packung","Haushalt"],
["Paddel","Sport & Freizeit"],
["Schaufelrad","Sonstiges"],
["Vorhängeschloss","Haushalt"],
["Pinsel","Werkzeug"],
["Schlafanzug","Kleidung"],
["Palast","Sonstiges"],
["Panflöte","Musik"],
["Küchenrolle","Küche"],
["Fallschirm","Sport & Freizeit"],
["Barren","Sport & Freizeit"],
["Gartenbank","Garten"],
["Parkuhr","Sonstiges"],
["Zugwaggon","Fahrzeug"],
["Terrasse","Garten"],
["Münztelefon","Sonstiges"],
["Sockel","Deko"],
["Federmäppchen","Büro"],
["Anspitzer","Büro"],
["Parfüm","Bad & Pflege"],
["Petrischale","Sonstiges"],
["Kopierer","Elektronik"],
["Plektrum","Musik"],
["Pickelhaube","Kleidung"],
["Lattenzaun","Garten"],
["Pick-up","Fahrzeug"],
["Steg","Sonstiges"],
["Sparschwein","Haushalt"],
["Tablettendose","Bad & Pflege"],
["Kissen","Haushalt"],
["Tischtennisball","Sport & Freizeit"],
["Windrad","Spielzeug"],
["Piratenschiff","Fahrzeug"],
["Krug","Küche"],
["Hobel","Werkzeug"],
["Planetarium","Sonstiges"],
["Plastiktüte","Haushalt"],
["Abtropfgestell","Küche"],
["Pflug","Sonstiges"],
["Saugglocke","Haushalt"],
["Sofortbildkamera","Elektronik"],
["Stange","Sonstiges"],
["Polizeiwagen","Fahrzeug"],
["Poncho","Kleidung"],
["Billardtisch","Sport & Freizeit"],
["Limoflasche","Lebensmittel"],
["Blumentopf","Garten"],
["Töpferscheibe","Werkzeug"],
["Bohrmaschine","Werkzeug"],
["Teppich","Haushalt"],
["Drucker","Elektronik"],
["Gefängnis","Sonstiges"],
["Geschoss","Sonstiges"],
["Beamer","Elektronik"],
["Puck","Sport & Freizeit"],
["Boxsack","Sport & Freizeit"],
["Handtasche","Taschen"],
["Federkiel","Büro"],
["Steppdecke","Haushalt"],
["Rennwagen","Fahrzeug"],
["Tennisschläger","Sport & Freizeit"],
["Heizkörper","Haushalt"],
["Radio","Elektronik"],
["Radioteleskop","Sonstiges"],
["Regentonne","Garten"],
["Wohnmobil","Fahrzeug"],
["Angelrolle","Sport & Freizeit"],
["Kamera","Elektronik"],
["Kühlschrank","Küche"],
["Fernbedienung","Elektronik"],
["Restaurant","Sonstiges"],
["Revolver","Sonstiges"],
["Gewehr","Sonstiges"],
["Schaukelstuhl","Möbel"],
["Drehspieß","Küche"],
["Radiergummi","Büro"],
["Rugbyball","Sport & Freizeit"],
["Lineal","Büro"],
["Turnschuh","Schuhe"],
["Tresor","Haushalt"],
["Sicherheitsnadel","Haushalt"],
["Salzstreuer","Küche"],
["Sandale","Schuhe"],
["Wickelrock","Kleidung"],
["Saxofon","Musik"],
["Schwertscheide","Sonstiges"],
["Waage","Haushalt"],
["Schulbus","Fahrzeug"],
["Segelschiff","Fahrzeug"],
["Anzeigetafel","Sonstiges"],
["Bildschirm","Elektronik"],
["Schraube","Werkzeug"],
["Schraubendreher","Werkzeug"],
["Sicherheitsgurt","Fahrzeug"],
["Nähmaschine","Haushalt"],
["Schild","Sonstiges"],
["Schuhe","Schuhe"],
["Raumteiler","Möbel"],
["Einkaufskorb","Taschen"],
["Einkaufswagen","Sonstiges"],
["Schaufel","Garten"],
["Duschhaube","Bad & Pflege"],
["Duschvorhang","Bad & Pflege"],
["Ski","Sport & Freizeit"],
["Sturmhaube","Kleidung"],
["Schlafsack","Sport & Freizeit"],
["Rechenschieber","Büro"],
["Schiebetür","Haushalt"],
["Spielautomat","Sonstiges"],
["Schnorchel","Sport & Freizeit"],
["Schneemobil","Fahrzeug"],
["Schneepflug","Fahrzeug"],
["Seifenspender","Bad & Pflege"],
["Fußball","Sport & Freizeit"],
["Socke","Kleidung"],
["Solarkollektor","Sonstiges"],
["Sombrero","Kleidung"],
["Suppenschüssel","Küche"],
["Tastatur","Elektronik"],
["Heizlüfter","Haushalt"],
["Raumfähre","Fahrzeug"],
["Pfannenwender","Küche"],
["Motorboot","Fahrzeug"],
["Spinnennetz","Sonstiges"],
["Spindel","Haushalt"],
["Sportwagen","Fahrzeug"],
["Strahler","Haushalt"],
["Bühne","Sonstiges"],
["Dampflok","Fahrzeug"],
["Bogenbrücke","Sonstiges"],
["Steeldrum","Musik"],
["Stethoskop","Sonstiges"],
["Stola","Kleidung"],
["Steinmauer","Garten"],
["Stoppuhr","Sport & Freizeit"],
["Ofen","Haushalt"],
["Sieb","Küche"],
["Straßenbahn","Fahrzeug"],
["Trage","Sonstiges"],
["Schlafsofa","Möbel"],
["Stupa","Sonstiges"],
["U-Boot","Fahrzeug"],
["Anzug","Kleidung"],
["Sonnenuhr","Garten"],
["Brille","Kleidung"],
["Sonnenbrille","Kleidung"],
["Sonnencreme","Bad & Pflege"],
["Hängebrücke","Sonstiges"],
["Wischmopp","Haushalt"],
["Sweatshirt","Kleidung"],
["Badehose","Kleidung"],
["Schaukel","Garten"],
["Lichtschalter","Haushalt"],
["Spritze","Bad & Pflege"],
["Tischlampe","Haushalt"],
["Panzer","Fahrzeug"],
["Tonbandgerät","Elektronik"],
["Teekanne","Küche"],
["Teddybär","Spielzeug"],
["Fernseher","Elektronik"],
["Tennisball","Sport & Freizeit"],
["Reetdach","Sonstiges"],
["Vorhang","Haushalt"],
["Fingerhut","Haushalt"],
["Dreschmaschine","Fahrzeug"],
["Thron","Möbel"],
["Ziegeldach","Sonstiges"],
["Toaster","Küche"],
["Tabakwaren","Sonstiges"],
["Toilette","Bad & Pflege"],
["Fackel","Sonstiges"],
["Totempfahl","Sonstiges"],
["Abschleppwagen","Fahrzeug"],
["Spielzeug","Spielzeug"],
["Traktor","Fahrzeug"],
["Sattelzug","Fahrzeug"],
["Tablett","Küche"],
["Trenchcoat","Kleidung"],
["Dreirad","Spielzeug"],
["Trimaran","Fahrzeug"],
["Stativ","Elektronik"],
["Triumphbogen","Sonstiges"],
["Oberleitungsbus","Fahrzeug"],
["Posaune","Musik"],
["Bottich","Haushalt"],
["Drehkreuz","Sonstiges"],
["Schreibmaschine","Büro"],
["Regenschirm","Haushalt"],
["Einrad","Sport & Freizeit"],
["Klavier","Musik"],
["Staubsauger","Haushalt"],
["Vase","Deko"],
["Gewölbe","Sonstiges"],
["Samtstoff","Haushalt"],
["Automat","Sonstiges"],
["Messgewand","Kleidung"],
["Viadukt","Sonstiges"],
["Geige","Musik"],
["Volleyball","Sport & Freizeit"],
["Waffeleisen","Küche"],
["Wanduhr","Haushalt"],
["Geldbörse","Taschen"],
["Kleiderschrank","Möbel"],
["Kampfflugzeug","Fahrzeug"],
["Waschbecken","Bad & Pflege"],
["Waschmaschine","Haushalt"],
["Trinkflasche","Küche"],
["Wasserkanister","Haushalt"],
["Wasserturm","Sonstiges"],
["Tonkrug","Küche"],
["Trillerpfeife","Sport & Freizeit"],
["Perücke","Bad & Pflege"],
["Fliegengitter","Haushalt"],
["Rollo","Haushalt"],
["Krawatte","Kleidung"],
["Weinflasche","Lebensmittel"],
["Tragfläche","Fahrzeug"],
["Wok","Küche"],
["Kochlöffel","Küche"],
["Wolle","Haushalt"],
["Holzzaun","Garten"],
["Wrack","Sonstiges"],
["Segelboot","Fahrzeug"],
["Jurte","Sonstiges"],
["Webseite","Elektronik"],
["Comic","Bücher & Medien"],
["Kreuzworträtsel","Bücher & Medien"],
["Straßenschild","Sonstiges"],
["Ampel","Sonstiges"],
["Buch","Bücher & Medien"],
["Speisekarte","Sonstiges"],
["Teller","Küche"],
["Guacamole","Lebensmittel"],
["Brühe","Lebensmittel"],
["Eintopf","Lebensmittel"],
["Dessert","Lebensmittel"],
["Eiscreme","Lebensmittel"],
["Eis am Stiel","Lebensmittel"],
["Baguette","Lebensmittel"],
["Bagel","Lebensmittel"],
["Brezel","Lebensmittel"],
["Cheeseburger","Lebensmittel"],
["Hotdog","Lebensmittel"],
["Kartoffelbrei","Lebensmittel"],
["Weißkohl","Lebensmittel"],
["Brokkoli","Lebensmittel"],
["Blumenkohl","Lebensmittel"],
["Zucchini","Lebensmittel"],
["Spaghettikürbis","Lebensmittel"],
["Eichelkürbis","Lebensmittel"],
["Butternusskürbis","Lebensmittel"],
["Gurke","Lebensmittel"],
["Artischocke","Lebensmittel"],
["Paprika","Lebensmittel"],
["Kardone","Lebensmittel"],
["Pilz","Lebensmittel"],
["Apfel","Lebensmittel"],
["Erdbeere","Lebensmittel"],
["Orange","Lebensmittel"],
["Zitrone","Lebensmittel"],
["Feige","Lebensmittel"],
["Ananas","Lebensmittel"],
["Banane","Lebensmittel"],
["Jackfrucht","Lebensmittel"],
["Cherimoya","Lebensmittel"],
["Granatapfel","Lebensmittel"],
["Heu","Sonstiges"],
["Spaghetti Carbonara","Lebensmittel"],
["Schokoladensoße","Lebensmittel"],
["Teig","Lebensmittel"],
["Hackbraten","Lebensmittel"],
["Pizza","Lebensmittel"],
["Pastete","Lebensmittel"],
["Burrito","Lebensmittel"],
["Rotwein","Lebensmittel"],
["Espresso","Lebensmittel"],
["Tasse","Küche"],
["Eierlikör","Lebensmittel"],
["Gebirge","Sonstiges"],
["Seifenblase","Spielzeug"],
["Klippe","Sonstiges"],
["Korallenriff","Sonstiges"],
["Geysir","Sonstiges"],
["Seeufer","Sonstiges"],
["Landzunge","Sonstiges"],
["Sandbank","Sonstiges"],
["Strand","Sonstiges"],
["Tal","Sonstiges"],
["Vulkan","Sonstiges"],
["Baseballspieler","Sonstiges"],
["Bräutigam","Sonstiges"],
["Taucher","Sonstiges"],
["Raps","Pflanze"],
["Gänseblümchen","Pflanze"],
["Frauenschuh","Pflanze"],
["Mais","Lebensmittel"],
["Eichel","Pflanze"],
["Hagebutte","Pflanze"],
["Kastanie","Pflanze"],
["Korallenpilz","Pflanze"],
["Blätterpilz","Pflanze"],
["Lorchel","Pflanze"],
["Stinkmorchel","Pflanze"],
["Erdstern","Pflanze"],
["Klapperschwamm","Pflanze"],
["Steinpilz","Pflanze"],
["Maiskolben","Lebensmittel"],
["Toilettenpapier","Bad & Pflege"]
];
